#选择项目运行环境
spring:
  profiles:
    active: test
  #thymeleaf start
  thymeleaf:
    #静态资源前缀
    prefix: classpath:/templates/
    #静态资源后缀
    suffix: .html
    #去除thymeleaf的严格校验
    mode: LEGACYHTML5
    #页面编码格式
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    #文档MIME类型
    servlet:
      content-type: text/html
  #thymeleaf end
  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinyougoudb
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  type-aliases-package: com.boynextdoor.oldfaggot.entity
  mapper-locations: classpath:**/xml/*.xml

#引入其他的yml文件
spring.profiles.include: 'bean'

#
#多个环境的配置用---隔开
---
spring:
  profiles: dev
server:
  port: 8080

---
spring:
  profiles: test

server:
  port: 8090